---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/version: 3.1.0.4875-ls41
  name: lidarr
spec:
  selector:
    app.kubernetes.io/name: lidarr
  ports:
  - name: http-lidarr
    port: 8686
    targetPort: 8686
