---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: searxng
  namespace: searxng
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: searxng
  groups:
  - name: kubernetes
