---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/version: sha256_b2211b2ad11fc
  name: searxng
spec:
  selector:
    app.kubernetes.io/name: searxng
  ports:
  - name: http-searxng
    port: 8080
    targetPort: 8080
