---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 24h
  chartRef:
    kind: HelmChart
    name: k8up-chart
  timeout: 10m
  releaseName: k8up
  install:
    remediation:
      retries: 3
  values:
    k8up:
      envVars:
      - name: BACKUP_GLOBAL_SUCCESSFUL_JOBS_HISTORY_LIMIT
        value: "1"
