---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: qbittorrent
resources:
- deployment.yaml
- vmrule.yaml
- vault-secrets.yaml
- scripts-configmap.yaml
- vpn-probe-configmap.yaml
- qbittorrent-config-pvc.yaml
- media-pvc.yaml
- service.yaml
- network-policy.yaml
- gateway-ingress-network-policy.yaml
- egress-network-policy.yaml
- default-deny-egress.yaml
