---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: ""
  volumeName: qbittorrent-media
