---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  networkRouterRef:
    name: netbird-operator-config
    namespace: netbird
  serviceRef:
    name: jellyfin
