---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 24h
  chartRef:
    kind: HelmChart
    name: jellyfin-chart
  timeout: 10m
  releaseName: jellyfin
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentStrategy:
      type: Recreate
    extraInitContainers:
    - command:
      - sh
      - -c
      - mkdir -p /config/config && cp /pennant/branding.xml /config/config/branding.xml
      image: busybox
      name: pennant-branding
      volumeMounts:
      - mountPath: /config
        name: config
      - mountPath: /pennant
        name: pennant-theme
        readOnly: true
    extraVolumeMounts:
      mountPath: /dev/dri
      name: hwa-volume
    extraVolumes:
      name: hwa-volume
      hostPath:
        path: /dev/dri
    metrics:
      enabled: true
    nodeSelector:
      kubernetes.io/hostname: debian
    persistence:
      config:
        storageClass: nfs-local
      media:
        existingClaim: jellyfin-pvc
    resources:
      requests:
        gpu.intel.com/i915: "1"
      limits:
        gpu.intel.com/i915: "1"
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
    volumes:
    - name: pennant-theme
      configMap:
        name: jellyfin-theme
