---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: music-library-builder
  namespace: jellyfin
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: music-library-builder
  groups:
  - name: kubernetes
