---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: code-server-backup
  namespace: code-server
spec:
  backend:
    repoPasswordSecretRef:
      name: restic-repo-password-secret
      key: password
    s3:
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: kubernetes-backups-code-server
      accessKeyIDSecretRef:
        name: garage-backup-access-key-secret
        key: access-key-id
      secretAccessKeySecretRef:
        name: garage-backup-access-key-secret
        key: secret-access-key
  backup:
    schedule: 0 3 * * *
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      seccompProfile:
        type: RuntimeDefault
    podConfigRef:
      name: code-server-backup-pod
  prune:
    schedule: 0 5 * * 0
    retention:
      keepLast: 14
      keepWeekly: 8
---
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: code-server-backup-pod
  namespace: code-server
spec:
  template:
    spec:
      containers:
      - name: backup
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
