---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redlib
    app.kubernetes.io/version: b9cbf93
  name: redlib
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redlib
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redlib
        app.kubernetes.io/version: b9cbf93
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      automountServiceAccountToken: false
      containers:
      - image: code.netbird.nathalie-stiefsohn.eu/my-homelab/redlib:b9cbf93@sha256:6cafa9d2dc992a68e48768baa2aeab23a2b4cb15a4ea82fe265cbdc40ed0c85c
        name: redlib
        ports:
        - containerPort: 8080
          name: redlib
        env:
        - name: REDLIB_DEFAULT_THEME
          value: pennant
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
