---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: vault
  namespace: vault
spec:
  networkRouterRef:
    name: netbird-operator-config
    namespace: netbird
  serviceRef:
    name: vault-ui
