---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: vault
  namespace: vault
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: vault-ui
  groups:
  - name: kubernetes
