---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tandoor-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: tandoor
  minReplicaCount: 0
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Vienna
      start: 0 9 * * *
      end: 0 21 * * *
      desiredReplicas: "1"
