---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internal-gateway-acme
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: debian-storage
