---
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-gateway-dynamic
data:
  middlewares.yaml: |
    http:
      middlewares:
        headlamp-basic-auth:
          basicAuth:
            usersFile: /auth/headlamp
            realm: headlamp.netbird.nathalie-stiefsohn.eu
            removeHeader: true
        limes-basic-auth:
          basicAuth:
            usersFile: /auth/limes
            realm: limes.netbird.nathalie-stiefsohn.eu
            removeHeader: true
        vim-dojo-basic-auth:
          basicAuth:
            usersFile: /auth/vim-dojo
            realm: dojo.netbird.nathalie-stiefsohn.eu
            removeHeader: true
  routers.yaml: |
    http:
      routers:
        audiomuse-ai:
          rule: Host(`audiomuse.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: audiomuse-ai
        backup-dashboard:
          rule: Host(`backups.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: backup-dashboard
        code-server:
          rule: Host(`vscode.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: code-server
        daybook:
          rule: Host(`daybook.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: daybook
        flood:
          rule: Host(`transmission.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: flood
        forgejo:
          rule: Host(`code.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: forgejo
        headlamp:
          rule: Host(`headlamp.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: headlamp
          middlewares:
          - headlamp-basic-auth
        it-tools:
          rule: Host(`it-tools.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: it-tools
        jellyfin:
          rule: Host(`jellyfin.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: jellyfin
        kavita:
          rule: Host(`kavita.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: kavita
        limes:
          rule: Host(`limes.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: limes
          middlewares:
          - limes-basic-auth
        mail:
          rule: Host(`mail.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: mail
        music-library-builder:
          rule: Host(`music.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: music-library-builder
        neko:
          rule: Host(`neko.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: neko
        omni-tools:
          rule: Host(`omni-tools.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: omni-tools
        orrery:
          rule: Host(`orrery.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: orrery
        psono-client:
          rule: Host(`psono.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: psono-client
        psono-server:
          rule: Host(`psono-api.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: psono-server
        redlib:
          rule: Host(`redlib.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: redlib
        searxng:
          rule: Host(`searxng.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: searxng
        tandoor:
          rule: Host(`tandoor.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: tandoor
        vault:
          rule: Host(`vault.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: vault
        vim-dojo:
          rule: Host(`dojo.netbird.nathalie-stiefsohn.eu`)
          entryPoints:
          - websecure
          service: vim-dojo
          middlewares:
          - vim-dojo-basic-auth
  services.yaml: |
    http:
      services:
        audiomuse-ai:
          loadBalancer:
            servers:
            - url: http://audiomuse-ai.jellyfin.svc.cluster.local:8000
        backup-dashboard:
          loadBalancer:
            servers:
            - url: http://backup-dashboard.backup-dashboard.svc.cluster.local:8080
        code-server:
          loadBalancer:
            servers:
            - url: http://code-server.code-server.svc.cluster.local:8080
        daybook:
          loadBalancer:
            servers:
            - url: http://daybook.daybook.svc.cluster.local:8080
        flood:
          loadBalancer:
            servers:
            - url: http://flood.jellyfin.svc.cluster.local:3000
        forgejo:
          loadBalancer:
            servers:
            - url: http://forgejo-http.forgejo.svc.cluster.local:3000
        headlamp:
          loadBalancer:
            servers:
            - url: http://headlamp.headlamp.svc.cluster.local:80
        it-tools:
          loadBalancer:
            servers:
            - url: http://it-tools.it-tools.svc.cluster.local:8080
        jellyfin:
          loadBalancer:
            servers:
            - url: http://jellyfin.jellyfin.svc.cluster.local:8096
        kavita:
          loadBalancer:
            servers:
            - url: http://kavita.kavita.svc.cluster.local:5000
        limes:
          loadBalancer:
            servers:
            - url: http://limes.limes.svc.cluster.local:8080
        mail:
          loadBalancer:
            servers:
            - url: http://roundcube.mail.svc.cluster.local:8000
        music-library-builder:
          loadBalancer:
            servers:
            - url: http://music-library-builder.jellyfin.svc.cluster.local:8140
        neko:
          loadBalancer:
            servers:
            - url: http://neko.neko.svc.cluster.local:8080
        omni-tools:
          loadBalancer:
            servers:
            - url: http://omni-tools.omni-tools.svc.cluster.local:8080
        orrery:
          loadBalancer:
            servers:
            - url: http://orrery.orrery.svc.cluster.local:8080
        psono-client:
          loadBalancer:
            servers:
            - url: http://psono-client.psono.svc.cluster.local:80
        psono-server:
          loadBalancer:
            servers:
            - url: http://psono-server.psono.svc.cluster.local:80
        redlib:
          loadBalancer:
            servers:
            - url: http://redlib.redlib.svc.cluster.local:8080
        searxng:
          loadBalancer:
            servers:
            - url: http://searxng.searxng.svc.cluster.local:8080
        tandoor:
          loadBalancer:
            servers:
            - url: http://tandoor.tandoor.svc.cluster.local:8080
        vault:
          loadBalancer:
            servers:
            - url: http://vault-ui.vault.svc.cluster.local:8200
        vim-dojo:
          loadBalancer:
            servers:
            - url: http://vim-dojo.vim-dojo.svc.cluster.local:3000
  tcp.yaml: |
    tcp:
      routers:
        forgejo-ssh:
          rule: HostSNI(`*`)
          entryPoints:
          - forgejo-ssh
          service: forgejo-ssh
      services:
        forgejo-ssh:
          loadBalancer:
            servers:
            - address: forgejo-ssh.forgejo.svc.cluster.local:2222
