---
apiVersion: netbird.io/v1alpha1
kind: Group
metadata:
  name: internal-gateway
  namespace: internal-gateway
spec:
  name: internal-gateway
---
apiVersion: netbird.io/v1alpha1
kind: SetupKey
metadata:
  name: internal-gateway-setup-key
  namespace: internal-gateway
spec:
  name: internal-gateway
  ephemeral: true
  allowExtraDnsLabels: true
  autoGroups:
  - name: kubernetes
  - localRef:
      name: internal-gateway
---
apiVersion: netbird.io/v1alpha1
kind: SidecarProfile
metadata:
  name: internal-gateway
  namespace: internal-gateway
spec:
  setupKeyRef:
    name: internal-gateway-setup-key
  podSelector:
    matchLabels:
      app.kubernetes.io/name: internal-gateway
  extraDNSLabels:
  - affine
  - audiomuse
  - backups
  - transmission
  - code
  - headlamp
  - jellyfin
  - kavita
  - music
  - perses
  - redlib
  - searxng
  - tandoor
  - vault
  containerOverride:
    env:
    - name: NB_DISABLE_UPDATE_SETTINGS
      value: "false"
