---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-gateway-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-gateway-vault-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: internal-gateway-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: internal-gateway-vault-auth
spec:
  kubernetes:
    role: internal-gateway
    serviceAccount: internal-gateway-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: internal-gateway-acme-dns-static-secret
spec:
  vaultAuthRef: internal-gateway-vault-auth
  mount: kvv2
  type: kv-v2
  path: acme-dns/traefik
  refreshAfter: 10s
  destination:
    create: true
    name: acme-dns-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: internal-gateway-basic-auth-static-secret
spec:
  vaultAuthRef: internal-gateway-vault-auth
  mount: kvv2
  type: kv-v2
  path: internal-gateway/basic-auth
  refreshAfter: 10s
  destination:
    create: true
    name: internal-gateway-basic-auth-secret
