---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 24h
  chartRef:
    kind: HelmChart
    name: headlamp-chart
  timeout: 10m
  releaseName: headlamp
  install:
    remediation:
      retries: 3
  values:
    clusterRoleBinding:
      clusterRoleName: cluster-admin
      create: true
    config:
      extraArgs:
      - -default-light-theme=Pennant
      - -default-dark-theme=Pennant Dark
      inCluster: true
      oidc:
        secret:
          create: false
      unsafeUseServiceAccountToken: true
    fullnameOverride: headlamp
    image:
      tag: v0.45.0
    initContainers:
    - command:
      - sh
      - /plugin-installer/install-plugins.sh
      - /headlamp/plugins
      - flux
      - 0.7.0
      - 837dc962a4ca485b86b010e5a3463d3ffc71c51778125394f006a210921b7c65
      - keda
      - 0.1.2
      - 979996aa0d0efdbc852baf6977e178c955264e346fea2c82df94b2d58ef57501
      - cert-manager
      - 0.1.1
      - 2b06caae0a207e2c30ce0d21bc4d672ae0a71a2cffc23a4585199110533032ab
      image: ghcr.io/headlamp-k8s/headlamp:v0.45.0
      name: install-plugins
      resources:
        limits:
          cpu: 200m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 101
        runAsNonRoot: true
        runAsUser: 100
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
      - mountPath: /plugin-installer
        name: plugin-installer
        readOnly: true
      - mountPath: /headlamp/plugins
        name: plugins
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 101
      runAsNonRoot: true
      runAsUser: 100
      seccompProfile:
        type: RuntimeDefault
    service:
      port: 80
      type: ClusterIP
    serviceAccount:
      create: true
      name: headlamp
    volumeMounts:
    - mountPath: /headlamp/plugins
      name: plugins
    - mountPath: /headlamp/plugins/pennant
      name: pennant-plugin
      readOnly: true
    volumes:
    - configMap:
        name: headlamp-pennant-plugin
      name: pennant-plugin
    - emptyDir: {}
      name: plugins
    - configMap:
        name: headlamp-plugin-installer
      name: plugin-installer
  driftDetection:
    mode: warn
