---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: code-server
  namespace: code-server
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: code-server
  groups:
  - name: kubernetes
