---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/version: v3.5.2
  name: flaresolverr
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
  ports:
  - name: http-flaresolverr
    port: 8191
    targetPort: 8191
