---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: egress-proxy
    app.kubernetes.io/version: sha256_8f9269b0b5b7b
  name: egress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: egress-proxy
  template:
    metadata:
      annotations:
        homelab/egress-proxy-config-hash: 39e80f9048c20a20d1570f3e0a6621e183779befec1704e638c0dcb9ea116468
      labels:
        app.kubernetes.io/name: egress-proxy
        app.kubernetes.io/version: sha256_8f9269b0b5b7b
    spec:
      containers:
      - command:
        - /usr/bin/tinyproxy
        - -d
        - -c
        - /etc/tinyproxy/tinyproxy.conf
        image: kalaksi/tinyproxy@sha256:8f9269b0b5b7b872b2fe8471299330c9fcf2ffb12eebdbb152feb7b9084f866a
        name: egress-proxy
        ports:
        - containerPort: 8888
          name: proxy
        volumeMounts:
        - mountPath: /etc/tinyproxy
          name: config
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 57981
          runAsGroup: 57981
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      volumes:
      - name: config
        configMap:
          name: egress-proxy-config
      securityContext:
        seccompProfile:
          type: RuntimeDefault
