---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: egress-proxy
    app.kubernetes.io/version: sha256_8f9269b0b5b7b
  name: egress-proxy
spec:
  selector:
    app.kubernetes.io/name: egress-proxy
  ports:
  - name: proxy
    port: 8888
    targetPort: 8888
