---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orrery-layout-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Mi
  storageClassName: nfs-remote
