---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: orrery
  namespace: orrery
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: orrery
  groups:
  - name: kubernetes
