---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gameyfin-games
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: ""
  volumeName: gameyfin-gameyfin-games
