---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gameyfin
resources:
- deployment.yaml
- config-pvc.yaml
- gameyfin-games-pvc.yaml
- service.yaml
- vault-secrets.yaml
- network-policy.yaml
- gateway-ingress-network-policy.yaml
- egress-network-policy.yaml
- default-deny-egress.yaml
