---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbird-operator-repo
spec:
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
  interval: 24h
  ref:
    tag: 0.4.1
