---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/version: 2024.10.22-7ca5933
  name: it-tools
spec:
  selector:
    app.kubernetes.io/name: it-tools
  ports:
  - name: http
    port: 8080
    targetPort: 8080
