---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: changedetection
    app.kubernetes.io/version: 0.60.4
  name: changedetection
spec:
  selector:
    app.kubernetes.io/name: changedetection
  ports:
  - name: http
    port: 5000
    targetPort: 5000
