---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zyme
    app.kubernetes.io/version: 624acbd
  name: zyme
spec:
  selector:
    app.kubernetes.io/name: zyme
  ports:
  - name: http
    port: 8080
    targetPort: 8080
