---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: anki-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: changedetection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: daybook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: egress-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: fourget
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: gameyfin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: glitchtip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: helium-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: homelab-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: it-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: jellyfin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: kavita
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: mail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: neko
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: ntfy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: omni-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: orrery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: paperless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: psono
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: radicale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: redlib
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: rimworld-together
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: stirling-pdf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: tandoor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: tare
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: trilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: valkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: victoria-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: vim-dojo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-operate
  namespace: zyme
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos-operate
subjects:
- kind: ServiceAccount
  name: pharos
  namespace: pharos
