---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: helium-services
  namespace: helium-services
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: helium-services
  groups:
  - name: kubernetes
