---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: tare-crawl
    app.kubernetes.io/version: e8ad7d4
  name: tare-crawl
spec:
  schedule: 30 3 * * *
  timeZone: Europe/Vienna
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app.kubernetes.io/name: tare-crawl
            app.kubernetes.io/version: e8ad7d4
        spec:
          imagePullSecrets:
          - name: forgejo-registry-secret
          automountServiceAccountToken: false
          enableServiceLinks: false
          containers:
          - args:
            - bff/src/Crawl.res.mjs
            image: code.netbird.nathalie-stiefsohn.eu/my-homelab/tare:e8ad7d4@sha256:2298b585123d79ddf1d844a7c9469d21e0d6cf5bb5fcca2991ff3ce3fb559a96
            name: tare-crawl
            env:
            - name: TZ
              value: Europe/Vienna
            - name: TARE_DATABASE_URL
              value: postgres://postgres-rw.postgres.svc.cluster.local:5432/tare
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: tare-db-secret
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: tare-db-secret
            - name: HTTPS_PROXY
              value: http://gluetun-proxy.gluetun-proxy.svc.cluster.local:8888
            resources:
              requests:
                cpu: 50m
                memory: 192Mi
              limits:
                cpu: 1000m
                memory: 768Mi
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
