---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tare
    app.kubernetes.io/version: 5fd826b
  name: tare
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tare
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tare
        app.kubernetes.io/version: 5fd826b
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
      - image: code.netbird.nathalie-stiefsohn.eu/my-homelab/tare:5fd826b@sha256:67cde4480e4a53f6326b1da4b57a0735b5ba497fe23f492675dc06e541d9b0ca
        name: tare
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TZ
          value: Europe/Vienna
        - name: TARE_DATABASE_URL
          value: postgres://postgres-rw.postgres.svc.cluster.local:5432/tare
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: tare-db-secret
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: tare-db-secret
        - name: WEB_ADDR
          value: :8080
        resources:
          requests:
            cpu: 10m
            memory: 96Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
      securityContext:
        seccompProfile:
          type: RuntimeDefault
