---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: ntfy
  namespace: ntfy
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: ntfy
  groups:
  - name: kubernetes
