---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ntfy-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ntfy-vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ntfy-vault-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ntfy-vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: ntfy-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ntfy-vault-auth
spec:
  kubernetes:
    role: ntfy
    serviceAccount: ntfy-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ntfy-ntfy-auth-static-secret
spec:
  vaultAuthRef: ntfy-vault-auth
  mount: kvv2
  type: kv-v2
  path: ntfy/auth
  refreshAfter: 10s
  destination:
    create: true
    name: ntfy-auth-secret
