---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: mealie
  namespace: mealie
spec:
  networkRouterRef:
    name: netbird-operator-config
    namespace: netbird
  serviceRef:
    name: mealie
