---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: mealie
  namespace: mealie
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: mealie
  groups:
  - name: kubernetes
