---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: healthchecks
  namespace: healthchecks
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: healthchecks
  groups:
  - name: kubernetes
