---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seerr-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seerr-vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seerr-vault-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seerr-vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: seerr-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: seerr-vault-auth
spec:
  kubernetes:
    role: seerr
    serviceAccount: seerr-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seerr-seerr-db-static-secret
spec:
  vaultAuthRef: seerr-vault-auth
  mount: kvv2
  type: kv-v2
  path: seerr/db
  refreshAfter: 10s
  destination:
    create: true
    name: seerr-db-secret
  rolloutRestartTargets:
  - kind: Deployment
    name: seerr
