package cli

import (
	"fmt"
	"kubernetes/pkg/schema/cluster/infrastructure/keda"
	"kubernetes/pkg/schema/generator"
	"os"
	"testing"
)

var dummyMeta = generator.GeneratorMeta{
	Name:          "jellyfin",
	Namespace:     "jellyfin",
	GeneratorType: generator.App,
	ClusterUrl:    "jellyfin.jellyfin.svc.cluster.local",
	Port:          8096,
	Helm: &generator.Helm{
		Url:     "https://jellyfin.github.io/jellyfin-helm",
		Chart:   "jellyfin",
		Version: "10.7.7",
	},
	Caddy: &generator.Caddy{
		DNSName:                    "jellyfin.cluster",
		WebsocketSupportIsRequired: true,
	},
	KedaScaling: &keda.ScaledObjectTriggerMeta{
		Timezone:        "Europe/Vienna",
		Start:           "0 7 * * *",
		End:             "0 1 * * *",
		DesiredReplicas: "1",
	},
	DependsOnGenerators: []string{},
}

var outDir = "."

func TestOutputFilesExist(t *testing.T) {
	generateGoFiles(dummyMeta, outDir)
	_, err := os.Open(fmt.Sprintf("%v/main.go", outDir))
	if err != nil {
		t.Error("Could not find file generated by generateGoFiles")
	}
	os.Remove(fmt.Sprintf("%v/main.go", outDir))
}
