---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: homelab-docs
  namespace: homelab-docs
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: homelab-docs
  groups:
  - name: kubernetes
