---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: flood
  namespace: jellyfin
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: flood
  groups:
  - name: kubernetes
