---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-vault-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless-vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: paperless-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: paperless-vault-auth
spec:
  kubernetes:
    role: paperless
    serviceAccount: paperless-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-paperless-oidc-static-secret
spec:
  vaultAuthRef: paperless-vault-auth
  mount: kvv2
  type: kv-v2
  path: paperless/oidc
  refreshAfter: 10s
  destination:
    create: true
    name: paperless-oidc-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-paperless-app-static-secret
spec:
  vaultAuthRef: paperless-vault-auth
  mount: kvv2
  type: kv-v2
  path: paperless/app
  refreshAfter: 10s
  destination:
    create: true
    name: paperless-secret
