---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: glitchtip
  namespace: glitchtip
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: glitchtip
  groups:
  - name: kubernetes
