---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-repo
  timeout: 10m
  releaseName: victoria-metrics
  install:
    remediation:
      retries: 3
  values:
    defaultDashboards:
      enabled: false
    grafana:
      enabled: false
    kubelet:
      enabled: true
      vmScrapes:
        cadvisor:
          enabled: true
          spec:
            bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            honorLabels: true
            metricRelabelConfigs:
            - action: keep
              regex: container_cpu_usage_seconds_total|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_cfs_throttled_seconds_total|container_memory_rss|container_memory_working_set_bytes|container_memory_cache|container_memory_swap|container_memory_usage_bytes|container_oom_events_total|container_fs_reads_bytes_total|container_fs_writes_bytes_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_spec_cpu_quota|container_spec_cpu_period|container_spec_memory_limit_bytes|machine_cpu_cores|machine_memory_bytes|cadvisor_version_info
              sourceLabels:
              - __name__
            - action: labeldrop
              regex: ^(feature_node_kubernetes_io|beta_kubernetes_io|gpu_intel_com|intel_feature_node_kubernetes_io|node_kubernetes_io_instance_type).*
            path: /metrics/cadvisor
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
        kubelet:
          enabled: true
          spec:
            bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            honorLabels: true
            metricRelabelConfigs:
            - action: labeldrop
              regex: ^(feature_node_kubernetes_io|beta_kubernetes_io|gpu_intel_com|intel_feature_node_kubernetes_io|node_kubernetes_io_instance_type).*
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
        probes:
          enabled: true
          spec:
            bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            honorLabels: true
            metricRelabelConfigs:
            - action: labeldrop
              regex: ^(feature_node_kubernetes_io|beta_kubernetes_io|gpu_intel_com|intel_feature_node_kubernetes_io|node_kubernetes_io_instance_type).*
            path: /metrics/probes
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
        resource:
          enabled: true
          spec:
            bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            honorLabels: true
            metricRelabelConfigs:
            - action: labeldrop
              regex: ^(feature_node_kubernetes_io|beta_kubernetes_io|gpu_intel_com|intel_feature_node_kubernetes_io|node_kubernetes_io_instance_type).*
            path: /metrics/resource
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
    nameOverride: vmks
    vmagent:
      spec:
        inlineScrapeConfig: |
          
          - job_name: cilium-agent
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names: [kube-system]
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_k8s_app]
                regex: cilium
                action: keep
              - source_labels: [__meta_kubernetes_pod_container_port_number]
                regex: "9962"
                action: keep
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - target_label: job
                replacement: cilium-agent
          
          - job_name: cilium-operator
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names: [kube-system]
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_name]
                regex: cilium-operator
                action: keep
              - source_labels: [__meta_kubernetes_pod_container_port_number]
                regex: "9963"
                action: keep
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - target_label: job
                replacement: cilium-operator
    vmsingle:
      spec:
        extraArgs:
          maxLabelsPerTimeseries: "120"
        storage:
          storageClassName: nfs-remote
