---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gluetun-proxy-networkpolicy
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: fourget
      podSelector:
        matchLabels:
          app.kubernetes.io/name: fourget
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: neko
      podSelector:
        matchLabels:
          app.kubernetes.io/name: neko
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: helium-services
      podSelector:
        matchLabels:
          app.kubernetes.io/name: helium-services
