---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gluetun-proxy-networkpolicy
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: fourget
      podSelector:
        matchLabels:
          app.kubernetes.io/name: fourget
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: neko
      podSelector:
        matchLabels:
          app.kubernetes.io/name: neko
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: helium-services
      podSelector:
        matchLabels:
          app.kubernetes.io/name: helium-services
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: gameyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: gameyfin
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: sonarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: radarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: lidarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prowlarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: bazarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: seerr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: flaresolverr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: clamav
      podSelector:
        matchLabels:
          app.kubernetes.io/name: clamav-hash-lookup
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tare
      podSelector:
        matchLabels:
          app.kubernetes.io/name: tare-crawl
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tare
      podSelector:
        matchLabels:
          app.kubernetes.io/name: tare
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: music-library-builder
    ports:
    - port: 8888
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: music-library-builder
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tare
      podSelector:
        matchLabels:
          app.kubernetes.io/name: tare-crawl
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tare
      podSelector:
        matchLabels:
          app.kubernetes.io/name: tare
    ports:
    - port: 8001
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: victoria-metrics
    ports:
    - port: 9101
      protocol: TCP
