---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gluetun-proxy-networkpolicy
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: fourget
      podSelector:
        matchLabels:
          app.kubernetes.io/name: fourget
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: neko
      podSelector:
        matchLabels:
          app.kubernetes.io/name: neko
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: helium-services
      podSelector:
        matchLabels:
          app.kubernetes.io/name: helium-services
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: sonarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: radarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: lidarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prowlarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: bazarr
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: seerr
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: victoria-metrics
    ports:
    - port: 9101
      protocol: TCP
