---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: rimworld-together
  namespace: rimworld-together
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: rimworld-together
  groups:
  - name: kubernetes
