---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rimworld-together-networkpolicy
spec:
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: netbird
      podSelector:
        matchLabels:
          app.kubernetes.io/name: networkrouter
