---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rimworld-together-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: debian-storage
