package generators

var NFSRemoteClass = "nfs-remote"
var NFSLocalClass = "nfs-local-v2"
var DebianStorageClass = "debian-storage"
var PostgresCredsSecret = "postgres-creds-secret"
var MatrixPGCredsSecret = "matrix-pg-creds-secret"
var ForgejoPGCredsSecret = "forgejo-pg-creds-secret"
var MariaDBCredsSecret = "mariadb-creds-secret"
var NetbirdSecretName = "netbird-setup-key-vault-secret"
var NetbirdAPIKeySecretName = "netbird-mgmt-api-key"
var HetznerAPITokenSecretName = "hetzner-api-token-secret"
var NetbirdDomainBase = "cloud.nathalie-stiefsohn.eu"
var SynapseSecretName = "synpase-secret"
var DiscordBridgeSecretName = "discord-bridge-secret"
var WhatsappBridgeSecretName = "whatsapp-bridge-secret"
var ElasticSearchAdminSecretName = "elastic-search-admin-secret"
var ElasticSearchVectorSecretName = "elastic-search-vector-secret"
