---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lidarr-vpn-only-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
      podSelector:
        matchLabels:
          app.kubernetes.io/name: media-dns
    ports:
    - port: 5353
      protocol: UDP
    - port: 5353
      protocol: TCP
  - to:
    - podSelector: {}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres
    ports:
    - port: 5432
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: gluetun-proxy
      podSelector:
        matchLabels:
          app.kubernetes.io/name: gluetun-proxy
    ports:
    - port: 8888
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: qbittorrent
      podSelector:
        matchLabels:
          app.kubernetes.io/name: qbittorrent
    ports:
    - port: 8080
      protocol: TCP
    - port: 8081
      protocol: TCP
