---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: main-pg
resources:
- cnpg-cluster.yaml
- audiomuseai-db.yaml
- tandoor-db.yaml
- psono-db.yaml
- authelia-db.yaml
- healthchecks-db.yaml
- ntfy-db.yaml
- glitchtip-db.yaml
- zyme-db.yaml
- limes-db.yaml
- sonarr-main-db.yaml
- sonarr-log-db.yaml
- radarr-main-db.yaml
- radarr-log-db.yaml
- lidarr-main-db.yaml
- lidarr-log-db.yaml
- prowlarr-main-db.yaml
- prowlarr-log-db.yaml
- bazarr-db.yaml
- seerr-db.yaml
- network-policy.yaml
- k8up-schedule.yaml
