---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-pg-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: main-pg-vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: main-pg-vault-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: main-pg-vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: main-pg-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: main-pg-vault-auth
spec:
  kubernetes:
    role: main-pg
    serviceAccount: main-pg-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-psono-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: psono/db
  refreshAfter: 10s
  destination:
    create: true
    name: psono-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-authelia-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: authelia/db
  refreshAfter: 10s
  destination:
    create: true
    name: authelia-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-glitchtip-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: glitchtip/db
  refreshAfter: 10s
  destination:
    create: true
    name: glitchtip-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-healthchecks-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: healthchecks/db
  refreshAfter: 10s
  destination:
    create: true
    name: healthchecks-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-limes-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: limes/db
  refreshAfter: 10s
  destination:
    create: true
    name: limes-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-ntfy-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: ntfy/db
  refreshAfter: 10s
  destination:
    create: true
    name: ntfy-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-paperless-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: paperless/db
  refreshAfter: 10s
  destination:
    create: true
    name: paperless-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-tandoor-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: tandoor/db
  refreshAfter: 10s
  destination:
    create: true
    name: tandoor-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-zyme-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: zyme/db
  refreshAfter: 10s
  destination:
    create: true
    name: zyme-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-tare-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: tare/db
  refreshAfter: 10s
  destination:
    create: true
    name: tare-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-audiomuseai-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: audiomuseai/db
  refreshAfter: 10s
  destination:
    create: true
    name: audiomuseai-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-sonarr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: sonarr/db
  refreshAfter: 10s
  destination:
    create: true
    name: sonarr-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-radarr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: radarr/db
  refreshAfter: 10s
  destination:
    create: true
    name: radarr-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-lidarr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: lidarr/db
  refreshAfter: 10s
  destination:
    create: true
    name: lidarr-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-prowlarr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: prowlarr/db
  refreshAfter: 10s
  destination:
    create: true
    name: prowlarr-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-bazarr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: bazarr/db
  refreshAfter: 10s
  destination:
    create: true
    name: bazarr-db-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: main-pg-seerr-db-static-secret
spec:
  vaultAuthRef: main-pg-vault-auth
  mount: kvv2
  type: kv-v2
  path: seerr/db
  refreshAfter: 10s
  destination:
    create: true
    name: seerr-db-role
