---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neko-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: neko
  minReplicaCount: 0
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Vienna
      start: 0 7 * * *
      end: 0 0 * * *
      desiredReplicas: "1"
