---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: neko
    app.kubernetes.io/version: 3.1.5
  name: neko
spec:
  selector:
    app.kubernetes.io/name: neko
  ports:
  - name: http-neko
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: webrtc-neko
    port: 52000
    targetPort: 52000
    protocol: UDP
