---
apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
data:
  initialize.sh: "#!/bin/sh exec livekit-server --config /etc/livekit.yaml"
  livekit.yaml: |-
    
    port: 7880
    rtc:
      tcp_port: 7881
      port_range_start: 50000
      port_range_end: 50020
      use_external_ip: false
    
    turn:
      enabled: true
      domain: livekit.nathi.lol
      tls_port: 5349
      udp_port: 3478
      external_tls: true
    
    keys: {}
