---
apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: cluster-services
  labels:
    app.kubernetes.io/name: livekit
    app.kubernetes.io/version: latest
  name: livekit
spec:
  selector:
    app.kubernetes.io/name: livekit
  ports:
  - name: tcp-livekit
    port: 7880
    targetPort: 7880
    protocol: TCP
  - name: udp-livekit
    port: 7882
    targetPort: 7882
    protocol: UDP
