---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiomuse-ai
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/audiomuse-ai
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: redis
  - name: main-pg
  - name: vault-secrets-operator-config
  - name: media-dns
  serviceAccountName: flux-audiomuse-ai
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bazarr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/bazarr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-bazarr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gluetun-media
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: gluetun-media
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/gluetun-media
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: vault-secrets-operator-config
  serviceAccountName: flux-gluetun-media
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/jellyfin
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  - name: keda
  - name: intel-device-gpu-plugin
  serviceAccountName: flux-jellyfin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lidarr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/lidarr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-lidarr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-dns
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/media-dns
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  serviceAccountName: flux-media-dns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: music-library-builder
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/music-library-builder
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: gluetun-media
  - name: csi-driver-nfs
  - name: reflector
  - name: media-dns
  serviceAccountName: flux-music-library-builder
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/prowlarr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-prowlarr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: qbittorrent
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/qbittorrent
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  - name: vault-secrets-operator-config
  - name: sabnzbd
  serviceAccountName: flux-qbittorrent
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/radarr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-radarr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: qbittorrent
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/sabnzbd
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  serviceAccountName: flux-sabnzbd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/seerr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-seerr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jellyfin
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/mediaserver/sonarr
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: jellyfin
  - name: main-pg
  - name: csi-driver-nfs
  - name: gluetun-proxy
  - name: media-dns
  serviceAccountName: flux-sonarr
