---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: jaeger
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/jaeger
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: victoria-traces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: perses
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: perses
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/perses
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: victoria-metrics
  - name: csi-driver-nfs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: vector
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/vector
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: csi-driver-nfs
  - name: reflector
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: victoria-logs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/victoria-stack/victoria-logs
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: csi-driver-nfs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: victoria-metrics
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/victoria-stack/victoria-metrics
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: csi-driver-nfs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-traces
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: victoria-traces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/monitoring/victoria-stack/victoria-traces
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: csi-driver-nfs
