---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/monitoring/flux-notifications
  prune: true
  wait: false
  timeout: 10m
  healthChecks:
  - apiVersion: notification.toolkit.fluxcd.io/v1beta3
    kind: Provider
    name: alertmanager
    namespace: flux-system
  - apiVersion: notification.toolkit.fluxcd.io/v1beta3
    kind: Alert
    name: flux-errors
    namespace: flux-system
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: victoria-metrics
  - name: vault-secrets-operator-config
  serviceAccountName: flux-flux-notifications
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: vector
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/monitoring/vector
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  - name: reflector
  serviceAccountName: flux-privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: victoria-logs
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/monitoring/victoria-stack/victoria-logs
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  serviceAccountName: flux-victoria-logs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: victoria-metrics
  sourceRef:
    kind: GitRepository
    name: manifests
  path: ./cluster/monitoring/victoria-stack/victoria-metrics
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: namespaces
  - name: flux-rbac
  - name: csi-driver-nfs
  - name: reflector
  - name: vault-secrets-operator-config
  serviceAccountName: flux-victoria-metrics
