---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: affine
  namespace: affine
spec:
  networkRouterRef:
    name: netbird-operator-config
    namespace: netbird
  serviceRef:
    name: affine
