---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v2.4.0
  name: homepage
spec:
  selector:
    app.kubernetes.io/name: homepage
  ports:
  - name: http
    port: 3000
    targetPort: 3000
