---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: system-upgrade-controller
    app.kubernetes.io/version: v0.20.1@sha256_aaf4d
  name: system-upgrade-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: system-upgrade-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: system-upgrade-controller
        app.kubernetes.io/version: v0.20.1@sha256_aaf4d
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - "true"
      serviceAccountName: system-upgrade
      containers:
      - image: rancher/system-upgrade-controller:v0.20.1@sha256:aaf4dbf640579a6abfa6390aab927ee664f06814e33c371e69df9dd451ca153a
        name: system-upgrade-controller
        env:
        - name: SYSTEM_UPGRADE_CONTROLLER_NAME
          value: system-upgrade-controller
        - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SYSTEM_UPGRADE_CONTROLLER_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SYSTEM_UPGRADE_CONTROLLER_DEBUG
          value: "false"
        - name: SYSTEM_UPGRADE_CONTROLLER_LEADER_ELECT
          value: "true"
        - name: SYSTEM_UPGRADE_CONTROLLER_THREADS
          value: "2"
        - name: SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS
          value: "900"
        - name: SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT
          value: "99"
        - name: SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE
          value: rancher/kubectl:v1.34.4@sha256:0a0e7a52f82b0fb12c28de2aedcc57e33acf08b5bfb75b099a4d3b958182a1ec
        - name: SYSTEM_UPGRADE_JOB_PRIVILEGED
          value: "true"
        - name: SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH
          value: "900"
        - name: SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL
          value: 15m
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/etcd
        operator: Exists
        effect: NoExecute
