---
apiVersion: v1
kind: Service
metadata:
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: cluster-services
  labels:
    app.kubernetes.io/name: audiomuse-ai-flask
    app.kubernetes.io/version: sha256_344c8d39bfc9c
  name: audiomuse-ai
spec:
  selector:
    app.kubernetes.io/name: audiomuse-ai-flask
  ports:
  - name: http-audiomuse
    port: 8000
    targetPort: 8000
