---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: audiomuse-ai-worker
    app.kubernetes.io/version: sha256_344c8d39bfc9c
  name: audiomuse-ai-worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: audiomuse-ai-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audiomuse-ai-worker
        app.kubernetes.io/version: sha256_344c8d39bfc9c
    spec:
      containers:
      - image: ghcr.io/neptunehub/audiomuse-ai@sha256:344c8d39bfc9cf4b2e83ab4d48c99692003786a5ebd2f0bc443099dc9e238de8
        name: audiomuse-ai-worker
        ports:
        - containerPort: 8000
          name: worker
        volumeMounts:
        - mountPath: /app/temp_audio
          name: temp-volume
        env:
        - name: SERVICE_TYPE
          value: worker
        - name: CLAP_ENABLED
          value: "false"
        - name: JELLYFIN_USER_ID
          valueFrom:
            secretKeyRef:
              key: userid
              name: jellyfin-creds
        - name: JELLYFIN_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: jellyfin-creds
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-creds-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-creds-secret
        envFrom:
        - configMapRef:
            name: audiomuse-configmap
      volumes:
      - name: temp-volume
        persistentVolumeClaim:
          claimName: audiomuse-ai-pvc
