---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/version: 5.1.3-ls273
  name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
  - name: http-sabnzbd
    port: 8081
    targetPort: 8081
