---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: limes
    app.kubernetes.io/version: latest
  name: limes
spec:
  selector:
    app.kubernetes.io/name: limes
  ports:
  - name: http
    port: 8080
    targetPort: 8080
