---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  interval: 24h
  chartRef:
    kind: HelmChart
    name: intel-device-plugins-operator-chart
  timeout: 10m
  releaseName: intel-device-plugins-operator
  install:
    remediation:
      retries: 3
