---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-hash-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: nfs-local
