---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clamav-local-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Ti
  claimRef:
    kind: PersistentVolumeClaim
    name: clamav-local-pvc
    namespace: clamav
  mountOptions:
  - nfsvers=4.1
  - ro
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: debian/mnt/external_ssd
    volumeAttributes:
      server: debian
      share: /mnt/external_ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    k8up.io/backup: "false"
  name: clamav-local-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: clamav-local-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clamav-nas-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 20Ti
  claimRef:
    kind: PersistentVolumeClaim
    name: clamav-nas-pvc
    namespace: clamav
  mountOptions:
  - nfsvers=3
  - hard
  - nolock
  - ro
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nathisvault.netbird.nathalie-stiefsohn.eu/volume1/nfs
    volumeAttributes:
      server: nathisvault.netbird.nathalie-stiefsohn.eu
      share: /volume1/nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    k8up.io/backup: "false"
  name: clamav-nas-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: ""
  volumeName: clamav-nas-pv
