---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kavita
    app.kubernetes.io/version: 0.9.0.2
  name: kavita
spec:
  selector:
    app.kubernetes.io/name: kavita
  ports:
  - name: http-kavita
    port: 5000
    targetPort: 5000
