---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redlib
    app.kubernetes.io/version: af3839d
  name: redlib
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redlib
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redlib
        app.kubernetes.io/version: af3839d
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      automountServiceAccountToken: false
      containers:
      - image: code.netbird.nathalie-stiefsohn.eu/my-homelab/redlib:af3839d@sha256:95bd0e088988c96eaa5720cac72ac80b3840ad5cac1cdfd049dab910a6ada4a4
        name: redlib
        ports:
        - containerPort: 8080
          name: redlib
        env:
        - name: REDLIB_DEFAULT_THEME
          value: pennant
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
