---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redlib
    app.kubernetes.io/version: 67a8f9c
  name: redlib
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redlib
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redlib
        app.kubernetes.io/version: 67a8f9c
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      automountServiceAccountToken: false
      containers:
      - image: code.netbird.nathalie-stiefsohn.eu/my-homelab/redlib:67a8f9c@sha256:95f080faa8b23c62c95bb0a5224f928a1ecb3e16d553785fc57459262881e961
        name: redlib
        ports:
        - containerPort: 8080
          name: redlib
        env:
        - name: REDLIB_DEFAULT_THEME
          value: pennant
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
