---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: authelia
  namespace: authelia
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: authelia
  groups:
  - name: kubernetes
