---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-vault-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authelia-vault-token-reviewer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authelia-vault-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authelia-vault-token-reviewer
subjects:
- kind: ServiceAccount
  name: authelia-vault-serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authelia-vault-auth
spec:
  kubernetes:
    role: authelia
    serviceAccount: authelia-vault-serviceaccount
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authelia-secrets-static-secret
spec:
  vaultAuthRef: authelia-vault-auth
  mount: kvv2
  type: kv-v2
  path: authelia/secrets
  refreshAfter: 10s
  destination:
    create: true
    name: authelia-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authelia-users-static-secret
spec:
  vaultAuthRef: authelia-vault-auth
  mount: kvv2
  type: kv-v2
  path: authelia/users
  refreshAfter: 10s
  destination:
    create: true
    name: authelia-users-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authelia-oidc-clients-static-secret
spec:
  vaultAuthRef: authelia-vault-auth
  mount: kvv2
  type: kv-v2
  path: authelia/oidc-clients
  refreshAfter: 10s
  destination:
    create: true
    name: authelia-oidc-clients-secret
