---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config-template
data:
  garage.toml.tmpl: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "sqlite"
    
    replication_factor = 1
    
    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "garage.garage.svc.cluster.local:3901"
    rpc_secret = "__RPC_SECRET__"
    
    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.svc.cluster.local"
    
    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "__ADMIN_TOKEN__"
    metrics_token = "__METRICS_TOKEN__"
