---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: garage-networkpolicy
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: code-server
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: daybook
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: forgejo
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kavita
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: mail
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tandoor
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: vault
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: vim-dojo
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: backup-dashboard
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: vault-apply
    ports:
    - port: 3900
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: garage
    ports:
    - port: 3901
      protocol: TCP
    - port: 3903
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: victoria-metrics
    ports:
    - port: 3903
      protocol: TCP
