---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-remote
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-remote
