---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: roundcube
  namespace: mail
spec:
  networkRouterRef:
    name: k8s-network
    namespace: netbird
  serviceRef:
    name: roundcube
  groups:
  - name: kubernetes
