---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: roundcube
    app.kubernetes.io/version: sha256_c018c84f59872
  name: roundcube
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: roundcube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: roundcube
        app.kubernetes.io/version: sha256_c018c84f59872
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 33:33 /var/roundcube/db
        image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
        name: permission-fix
        volumeMounts:
        - mountPath: /var/roundcube/db
          name: roundcube-db-volume
      - command:
        - sh
        - /pennant/roundcube-skin-sources.sh
        - /pennant-skin
        - /pennant/_variables.less
        image: roundcube/roundcubemail@sha256:c018c84f59872905c1b8da9326bf2aece4ce3ea87add7de03f16850d3a830f7a
        name: pennant-skin-sources
        volumeMounts:
        - mountPath: /pennant
          name: pennant-scripts-volume
          readOnly: true
        - mountPath: /pennant-skin
          name: pennant-skin-volume
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      - command:
        - sh
        - /pennant/roundcube-skin-compile.sh
        - /pennant-skin
        image: code.netbird.nathalie-stiefsohn.eu/my-homelab/lessc@sha256:58bf86bb2cfe2975cd02f6ff76d5629f9b5950905929abd0209b0652295b1acc
        name: pennant-skin-compile
        volumeMounts:
        - mountPath: /pennant
          name: pennant-scripts-volume
          readOnly: true
        - mountPath: /pennant-skin
          name: pennant-skin-volume
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      automountServiceAccountToken: false
      containers:
      - image: roundcube/roundcubemail@sha256:c018c84f59872905c1b8da9326bf2aece4ce3ea87add7de03f16850d3a830f7a
        name: roundcube
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - mountPath: /var/roundcube/db
          name: roundcube-db-volume
        - mountPath: /var/roundcube/config
          name: roundcube-config-volume
          readOnly: true
        - mountPath: /var/roundcube/oidc
          name: roundcube-oidc-volume
          readOnly: true
        - mountPath: /pennant-skin
          name: pennant-skin-volume
          readOnly: true
        - mountPath: /entrypoint-tasks/post-setup
          name: pennant-task-volume
          readOnly: true
        env:
        - name: ROUNDCUBEMAIL_DEFAULT_HOST
          value: mail
        - name: ROUNDCUBEMAIL_DEFAULT_PORT
          value: "143"
        - name: ROUNDCUBEMAIL_SMTP_SERVER
          value: mail
        - name: ROUNDCUBEMAIL_SMTP_PORT
          value: "25"
        - name: ROUNDCUBEMAIL_DB_TYPE
          value: sqlite
        - name: ROUNDCUBEMAIL_SKIN
          value: elastic
        - name: TZ
          value: Europe/Vienna
        - name: ROUNDCUBE_OIDC_SCOPE
          value: openid profile email offline_access
        - name: ROUNDCUBE_OIDC_CLIENT_SECRET_FILE
          value: /var/roundcube/oidc/client-secret
        - name: ROUNDCUBE_URL
          value: https://mail.netbird.nathalie-stiefsohn.eu
        - name: ROUNDCUBE_OIDC_AUTHORITY
          value: https://auth.netbird.nathalie-stiefsohn.eu
        - name: ROUNDCUBE_OIDC_CLIENT_ID
          value: mail
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false
      volumes:
      - name: roundcube-db-volume
        persistentVolumeClaim:
          claimName: roundcube-pvc
      - name: roundcube-config-volume
        configMap:
          name: roundcube-config
      - name: roundcube-oidc-volume
        secret:
          secretName: mail-oidc-secret
          optional: true
      - name: pennant-scripts-volume
        configMap:
          name: roundcube-pennant-skin
      - name: pennant-skin-volume
        emptyDir: {}
      - name: pennant-task-volume
        configMap:
          name: roundcube-pennant-skin
          items:
          - key: roundcube-skin-install.sh
            path: pennant-skin.sh
          defaultMode: 365
