---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pharos
    app.kubernetes.io/version: bfbd5cf
  name: pharos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pharos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pharos
        app.kubernetes.io/version: bfbd5cf
    spec:
      imagePullSecrets:
      - name: forgejo-registry-secret
      serviceAccountName: pharos
      enableServiceLinks: false
      containers:
      - image: code.netbird.nathalie-stiefsohn.eu/my-homelab/pharos:bfbd5cf@sha256:3a7808af1f7f08c27f7efac3026913baa6e367d00980c08ea23697f49e935f12
        name: pharos
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: WEB_ADDR
          value: :8080
        - name: PHAROS_STATIC_ROOT
          value: /app/ui/dist
        - name: PHAROS_VL_URL
          value: http://victoria-logs.victoria-logs.svc.cluster.local:9428
        - name: PHAROS_OIDC_AUTHORITY
          value: https://auth.netbird.nathalie-stiefsohn.eu
        - name: PHAROS_OIDC_CLIENT_ID
          value: pharos
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
