---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pharos
    app.kubernetes.io/version: 7da1399
  name: pharos
spec:
  selector:
    app.kubernetes.io/name: pharos
  ports:
  - name: http
    port: 8080
    targetPort: 8080
