---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: psono-client
    app.kubernetes.io/version: sha256_487eb17619356
  name: psono-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: psono-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psono-client
        app.kubernetes.io/version: sha256_487eb17619356
    spec:
      automountServiceAccountToken: false
      containers:
      - image: psono/psono-client@sha256:487eb176193565f5ebdc9a9d6d610b9c0a832ca6b56221bf2703a526c97727d7
        name: psono-client
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PSONO_WEBCLIENT_CONFIG_JSON
          value: "{\"backend_servers\":[{\"title\":\"Homelab\",\"url\":\"https://psono-api.netbird.nathalie-stiefsohn.eu\",\"domain\":\"homelab.internal\"}],\"base_url\":\"https://psono.netbird.nathalie-stiefsohn.eu/\",\"allow_custom_server\":false,\"allow_registration\":false,\"allow_lost_password\":false,\"allow_delete_account\":false,\"authentication_methods\":[\"AUTHKEY\"],\"more_links\":[],\"theme\":{\"palette\":{\"background\":{\"default\":\"#090c0d\",\"paper\":\"#ffffff\"},\"primary\":{\"main\":\"#984a72\"},\"secondary\":{\"main\":\"#007495\"},\"action\":{\"disabledBackground\":\"#984a7280\"},\"lightGreyText\":{\"main\":\"#838b8e\",\"light\":\"#838b8e\",\"dark\":\"#838b8e\",\"contrastText\":\"#838b8e\"},\"greyText\":{\"main\":\"#666d71\",\"light\":\"#666d71\",\"dark\":\"#666d71\",\"contrastText\":\"#666d71\"},\"checked\":{\"main\":\"#984a72\",\"light\":\"#984a72\",\"dark\":\"#984a72\",\"contrastText\":\"#984a72\"},\"blueBackground\":{\"main\":\"#141819\",\"light\":\"#141819\",\"dark\":\"#141819\",\"contrastText\":\"#141819\"},\"badgeBackground\":{\"main\":\"#838b8e\",\"light\":\"#838b8e\",\"dark\":\"#838b8e\",\"contrastText\":\"#838b8e\"},\"appBarText\":{\"main\":\"#666d71\",\"light\":\"#666d71\",\"dark\":\"#666d71\",\"contrastText\":\"#666d71\"},\"appBarBackground\":{\"main\":\"#ffffff\",\"light\":\"#ffffff\",\"dark\":\"#ffffff\",\"contrastText\":\"#ffffff\"},\"appBarReadOnlyText\":{\"main\":\"#6d4700\",\"light\":\"#6d4700\",\"dark\":\"#6d4700\",\"contrastText\":\"#6d4700\"},\"appBarReadOnlyBackground\":{\"main\":\"#ffe9cd\",\"light\":\"#ffe9cd\",\"dark\":\"#ffe9cd\",\"contrastText\":\"#ffe9cd\"},\"baseBackground\":{\"main\":\"#e3e7e9\",\"light\":\"#e3e7e9\",\"dark\":\"#e3e7e9\",\"contrastText\":\"#e3e7e9\"},\"baseTitleBackground\":{\"main\":\"#f1f4f5\",\"light\":\"#f1f4f5\",\"dark\":\"#f1f4f5\",\"contrastText\":\"#f1f4f5\"},\"lightBackground\":{\"main\":\"#ffffff\",\"light\":\"#ffffff\",\"dark\":\"#ffffff\",\"contrastText\":\"#ffffff\"}}}}"
        - name: PSONO_SERVICE_WORKER_DISABLE
          value: "true"
        - name: TZ
          value: Europe/Vienna
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
